### ISSUE TITLE
Timing-Fehler beim LEVEL_SWITCHING

### ISSUE THREAD

**Issue by jstabenow** [datarhei/clappr-live#3]
Es gibt immer wieder Aussetzer beim auto. Wechsel auf die endgültige Bitrate (z.B. Level 0 auf 3), wodurch es zu einem kurzen Geruckel/Aussetzer kommt. 

Ich vermute, dass der Player die beiden Level nicht sync. bekommt und darum irgendwann kapituliert. Genau weiß ich es aber noch nicht. Da wir die Streams aber auch nicht wirklich sync. auf den Servern haben, ist dies recht naheliegend. 

Das Playerhandling sollte hier überprüft werden.

**Comment by ioppermann** [comment]
Der Level-Switch wird vom hls.js gemacht. Der clappr-player fummelt da nicht rein, wie ich das gesehen habe.

**Comment by jstabenow** [comment]
Genau, da haben wir ja schon gestern drüber gesprochen. Seitdem die Poster nicht mehr beim Level-Switch heruntergeladen werden, habe ich auch keine Aussetzer mehr. Und die Timing-Fehler entstehen einfach durch den Transportweg Kamera -> Wowza -> Cache -> Player. Sprich da kann der Player nix für -> Close
