### ISSUE TITLE
playInline Mode funktioniert nicht auf iOS

### ISSUE THREAD

**Issue by jstabenow** [datarhei/clappr-live#6]
Unter iOS startet der Player (mit und ohne Ads) das Video direkt im iOS-Player, was er jedoch nicht machen soll. Dafür gibt es eigentlich den Inline-Modus, welcher aktiviert ist, jedoch nicht korrekt funktioniert.

Folgend die knappe Doku zu der Funktion:
https://github.com/clappr/clappr/blob/dev/doc/BUILTIN_PLUGINS.md#playback-configuration

**Comment by ioppermann** [comment]
Hmm, bei mir funktionierts ... auch ein Touch bringt die mediaControl zum Vorschein.

![Foto 03 09 19, 09 31 35](https://user-images.githubusercontent.com/57445/64152994-1ead4480-ce2e-11e9-945c-123328dd2f39.png)

**Comment by jstabenow** [comment]
Hier mein Test ohne Ad:
https://player.livespotting.com/clappr2.html?id=vv28
```jscript
playback: {
  controls: true,
  playInline: true
}
```

Und hier mit Ad:
https://player.livespotting.com/clappr-ad.html?id=vv28
```jscript
playback: {
  controls: true,
  playInline: true,
  recycleVideo: Clappr.Browser.isMobile
}
```

Beides funktioniert bei mir echt miese. Auf dem Desktop (neuster Chrome, Safari und Firefox unter OSX 10.14.6) und auf dem Mobile (iPhone 6S mit iOS 12.4.1) scheinen jeweils die Media-Control vom Player und vom Browser/OS durch. Beim Mobile verschwinden dann auch noch wie [hier](https://github.com/datarhei/clappr-live/issues/7) beschrieben die Elemente, welche sich auch mangels Touch-Funktion nicht wiederherstellen lassen und die native Control-Bar bestehen bleibt. Also alles irgendwie ein totales Chaos.

![Bildschirmfoto 2019-09-03 um 11 02 03](https://user-images.githubusercontent.com/7462030/64159343-63d77380-ce3a-11e9-91bc-0c8778d401e2.png)
![Neue Notiz](https://user-images.githubusercontent.com/7462030/64159933-4d7de780-ce3b-11e9-9adf-2ee1d7ad5cc3.jpeg)

Vielleicht siehst Du ja irgend einen Fehler in meiner Config. Ich habe keinen gefunden.

**Comment by ioppermann** [comment]
Die Controls vom video-tag müssen explizt deaktiviert werden:

```
{
   ...
   disableVideoTagContextMenu: true,
   playback: {
       controls: false,
       playInline: true,
       recycleVideo: Clappr.Browser.isMobile
   } 
}

**Comment by jstabenow** [comment]
lol ich wollte gerade schreiben ... Ist mir auch gerade beim testen aufgefallen 👍

**Comment by jstabenow** [comment]
Ok, ich leg mich wieder hin ;-) -> Close
